<script>  
  import ImageComparison from "../../components/ImageComparison.svelte";
  import "fluent-svelte/theme.css";
  import CardContainer from "../../components/cards/CardContainer.svelte";
  import Card from "../../components/cards/Card.svelte";
</script>

<div class="container">
  <picture>
    <source
      srcset="/app-images/redditvideogenerator/logoDark.png"
      media="(prefers-color-scheme: dark)" />
    <img
      class="logo"
      alt="RedditVideoGenerator"
      src="/app-images/redditvideogenerator/logoLight.png" />
  </picture>

  <h2>
    For more information and details, please head here: <a
      class="links"
      href="https://github.com/Apollo199999999/RedditVideoGenerator/blob/main/README.md"
      >https://github.com/Apollo199999999/RedditVideoGenerator/blob/main/README.md</a>
  </h2>

  <CardContainer>
    <Card
      headerText="About"
      subtitleText="RedditVideoGenerator generates r/AskReddit videos and uploads them to YouTube automatically.">
      <ImageComparison
        srcLeft="/screenshots/redditvideogenerator/UILight.png"
        altLeft="Light Theme"
        srcRight="/screenshots/redditvideogenerator/UIDark.png"
        altRight="Dark Theme" />
    </Card>

    <Card
      headerText="Video"
      subtitleText=" RedditVideoGenerator is able to fully generate a 15 minute Reddit video, with background music courtesy of Kevin Macleod.">
      <iframe
        src="https://www.youtube.com/embed/0_h4B9_SXWU"
        title="YouTube video player"
        frameborder="0"
        class="video-player"
        allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
        allowfullscreen />
    </Card>

    <Card
      headerText="Thumbnail"
      subtitleText="RedditVideoGenerator also generates a thumbnail image, a title, and description for
      YouTube, all fully autonomously.">
      <img
        src="/screenshots/redditvideogenerator/SampleThumbnail.png"
        alt="Sample thumbnail generated by RedditVideoGenerator"
        class="thumbnail-img" />
    </Card>
  </CardContainer>
</div>

<style>
  .container {
    margin-top: 2em;
  }

  .logo {
    width: 100%;
    max-width: 600px;
  }

  .links {
    color: var(--fds-accent-text-primary);
    text-align: center;
    overflow-wrap: break-word;
    word-wrap: break-word;
    word-break: break-word;
    hyphens: auto;
  }

  .video-player,
  .thumbnail-img {
    width: 100%;
    height: unset;
    aspect-ratio: 16 / 9;
  }
</style>
