<script>
    import { TextBlock, InfoBar } from "fluent-svelte";
    import HeaderChip from "/src/components/HeaderChip.svelte";
    import "fluent-svelte/theme.css";
</script>

<div class="container">
    <div class="top">
        <HeaderChip>Feature</HeaderChip>

        <TextBlock variant="titleLarge" class="titleText"
            >Sample Video</TextBlock
        >

        <TextBlock variant="bodyLarge" class="bodyText"
            >Sample video generated by RedditVideoGenerator</TextBlock
        >
    </div>

    <div class="bottom">
        <iframe
            src="https://www.youtube.com/embed/0_h4B9_SXWU"
            title="YouTube video player"
            frameborder="0"
            class="video-player"
            allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
            allowfullscreen
        />
    </div>
</div>

<style>
    .container {
        height: 100%;
        display: flex;
        flex-flow: column;
        word-wrap: break-word;
        justify-content: center;
        text-align: center;
        overflow: hidden;
    }

    /* force the title to wrap if it is almost touching the edges */
    .top :global(.titleText) {
        display: block;
        margin-left: 5px;
        margin-right: 5px;
    }

    .top :global(.bodyText) {
        display: block;
        text-align: center;
        margin-top: 1.5em;
        max-width: 95%;
    }

    .bottom {
        flex-grow: 1;
        position: relative;
        min-width: 100%;
        margin-top: 1.5em;
    }

    .video-player {
        width: 100%;
        height: unset;
        aspect-ratio: 16 / 9;
    }
</style>
